#!/bin/bash -x

# Use apt-cache server to speed things up
sudo tee /etc/apt/apt.conf.d/01proxy <<EOF
Acquire::HTTP::Proxy "http://apt-cache.pdbld.f5net.com:3142";
Acquire::HTTPS::Proxy "false";
EOF


sudo apt-get update
sudo DEBIAN_FRONTEND=noninteractive apt-get install -y \
     devscripts \
     equivs \
     git \
     golang \
     golang-go.tools \
     m4 \
     make \
     python \
     python-dev \
     python-pip

# Install CLI for the Aptly Package Repo and create conf file to point to our repo server
sudo gem install aptly_cli -v 0.2.5
echo -e ":server: apt.pdbld.f5net.com\n:port: 8080\n:debug: false" | sudo tee /etc/aptly-cli.conf
