#!/bin/bash -x

DIR=$(realpath $(dirname $0))

# Setup the $GOPATH and any other variables needed by Go.
source ${DIR}/set-go-paths.sh
if [ ! -d $GOPATH ]; then
    mkdir -p $GOPATH
fi

# Install go race detection runtime. Unfortunately, this does not get
# automatically built and installed when the package is installed. This little
# hack ensure that it is built and it is installed in the system location so
# that even GB-built packages can use it.
sudo go install -v -race runtime/race
