#!/bin/bash -x

DIR=$(realpath $(dirname $0))

# Setup the $GOPATH and any other variables needed by Go.
sudo cp ${DIR}/set-go-paths.sh /etc/profile.d/.

# Install gb.
source ${DIR}/set-go-paths.sh
if [ ! -d $GOPATH ]; then
    mkdir -p $GOPATH
fi

git clone https://bldr-git.int.lineratesystems.com/mirror/gb.git $GOPATH/src/github.com/constabulary/gb
git -C $GOPATH/src/github.com/constabulary/gb checkout 2b9e9134
go install -v github.com/constabulary/gb/...
