FROM quay.io/f5networks/rhel8_base_builder:latest as base

ENV BASE_PATH "$GOPATH/src/github.com/F5Networks"
RUN mkdir -p "$BASE_PATH"
ENV REPO_NAME k8s-bigip-ctlr
WORKDIR "$BASE_PATH/$REPO_NAME"

ARG RUN_TESTS=0
ARG COVERALLS_TOKEN
ARG BUILD_VERSION
ARG BUILD_INFO
ARG LICENSE

# Copy Source code to workdir
COPY . .
COPY build-tools/help.md /tmp/
RUN  go-md2man -in /tmp/help.md -out /help.1 && rm -f /tmp/help.md && \
     /bin/bash -ex $BASE_PATH/$REPO_NAME/build-tools/rel-build.sh


FROM registry.redhat.io/ubi7/ubi-minimal as final

LABEL name="f5networks/k8s-bigip-ctlr" \
      vendor="F5 Networks" \
      # version - should be passed in via docker build
      url="http://clouddocs.f5.com/products/connectors/k8s-bigip-ctlr/latest/" \
      summary="F5 BIG-IP Controller for Kubernetes" \
      description="Manages F5 BIG-IP from Kubernetes" \
      run='docker run --name ${NAME} ${IMAGE} /app/bin/k8s-bigip-ctlr' \
      io.k8s.description="Manages F5 BIG-IP from Kubernetes" \
      io.k8s.display-name="F5 BIG-IP Controller for Kubernetes" \
      io.openshift.expose-services="" \
      io.openshift.tags="f5,f5networks,bigip,openshift,router"

ENV APPPATH /app

RUN mkdir -p "$APPPATH/bin" "$APPPATH/vendor/src/f5/schemas/" \
 && chmod -R 755 "$APPPATH"

WORKDIR $APPPATH
ARG BUILD_INFO
ARG VERSION_INFO

COPY $BASE_PATH/$REPO_NAME/build-tools/help.md /tmp/
COPY $BASE_PATH/$REPO_NAME/LICENSE /licenses/
COPY $BASE_PATH/$REPO_NAME/requirements.txt /tmp/requirements.txt
COPY ["$BASE_PATH/$REPO_NAME/schemas/as3-schema-3.25.0-3-cis.json", \
    "$BASE_PATH/$REPO_NAME/schemas/bigip-virtual-server_v0.1.0.json",\
    "$BASE_PATH/$REPO_NAME/schemas/bigip-virtual-server_v0.1.1.json",\
    "$BASE_PATH/$REPO_NAME/schemas/bigip-virtual-server_v0.1.2.json",\
    "$BASE_PATH/$REPO_NAME/schemas/bigip-virtual-server_v0.1.3.json",\
    "$BASE_PATH/$REPO_NAME/schemas/bigip-virtual-server_v0.1.4.json",\
    "$BASE_PATH/$REPO_NAME/schemas/bigip-virtual-server_v0.1.5.json",\
    "$BASE_PATH/$REPO_NAME/schemas/bigip-virtual-server_v0.1.6.json",\
    "$BASE_PATH/$REPO_NAME/schemas/bigip-virtual-server_v0.1.7.json",\
    "$APPPATH/vendor/src/f5/schemas/"]

COPY --from=base "/help.1" /

RUN microdnf --enablerepo=ubi-7 \
      --enablerepo=ubi-7-server-devtools-rpms --enablerepo=ubi-7-server-extras-rpms --enablerepo=ubi-7-server-optional-rpms --enablerepo=ubi-server-rhscl-7-rpms install --nodocs \
      rh-python36 git shadow-utils && \
    microdnf update && \
    microdnf --enablerepo=ubi-7 --enablerepo=ubi-7-server-devtools-rpms --enablerepo=ubi-7-server-extras-rpms --enablerepo=ubi-7-server-optional-rpms --enablerepo=ubi-server-rhscl-7-rpms update nss-tools nss-softokn nss-util && \
    source scl_source enable rh-python36 && \
    pip install --no-cache-dir --upgrade pip==20.0.2 && \
    pip install --no-cache-dir -r /tmp/requirements.txt && \
    python -m pip uninstall -y pip && \
    adduser ctlr && \
    microdnf remove git fipscheck fipscheck-lib  less libedit \
    libgnome-keyring openssh openssh-clients  perl-Git  perl-TermReadKey  perl-macros  rsync shadow-utils && \
    microdnf clean all \
    && echo "{\"version\": \"${VERSION_INFO}\", \"build\": \"${BUILD_INFO}\"}" \
          > $APPPATH/vendor/src/f5/VERSION_BUILD.json

COPY --from=base "/build/mnt/linux-amd64-release-go1.15/bin/k8s-bigip-ctlr" $APPPATH/bin/k8s-bigip-ctlr.real

# entrypoint to enable scl python at runtime
RUN echo $'#!/bin/sh\n\
	  source scl_source enable rh-python36\n\
	  exec $APPPATH/bin/k8s-bigip-ctlr.real "$@"' > $APPPATH/bin/k8s-bigip-ctlr && \
    chmod +x $APPPATH/bin/k8s-bigip-ctlr

# Enable CN Certificate validation
ENV GODEBUG x509ignoreCN=0

USER ctlr

# Run the run application in the projects bin directory.
CMD [ "/app/bin/k8s-bigip-ctlr" ]
