/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	cisv1 "github.com/F5Networks/k8s-bigip-ctlr/v3/config/apis/cis/v1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeExternalDNSes implements ExternalDNSInterface
type FakeExternalDNSes struct {
	Fake *FakeCisV1
	ns   string
}

var externaldnsesResource = schema.GroupVersionResource{Group: "cis.f5.com", Version: "v1", Resource: "externaldnses"}

var externaldnsesKind = schema.GroupVersionKind{Group: "cis.f5.com", Version: "v1", Kind: "ExternalDNS"}

// Get takes name of the externalDNS, and returns the corresponding externalDNS object, and an error if there is any.
func (c *FakeExternalDNSes) Get(ctx context.Context, name string, options v1.GetOptions) (result *cisv1.ExternalDNS, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(externaldnsesResource, c.ns, name), &cisv1.ExternalDNS{})

	if obj == nil {
		return nil, err
	}
	return obj.(*cisv1.ExternalDNS), err
}

// List takes label and field selectors, and returns the list of ExternalDNSes that match those selectors.
func (c *FakeExternalDNSes) List(ctx context.Context, opts v1.ListOptions) (result *cisv1.ExternalDNSList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(externaldnsesResource, externaldnsesKind, c.ns, opts), &cisv1.ExternalDNSList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &cisv1.ExternalDNSList{ListMeta: obj.(*cisv1.ExternalDNSList).ListMeta}
	for _, item := range obj.(*cisv1.ExternalDNSList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested externalDNSes.
func (c *FakeExternalDNSes) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(externaldnsesResource, c.ns, opts))

}

// Create takes the representation of a externalDNS and creates it.  Returns the server's representation of the externalDNS, and an error, if there is any.
func (c *FakeExternalDNSes) Create(ctx context.Context, externalDNS *cisv1.ExternalDNS, opts v1.CreateOptions) (result *cisv1.ExternalDNS, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(externaldnsesResource, c.ns, externalDNS), &cisv1.ExternalDNS{})

	if obj == nil {
		return nil, err
	}
	return obj.(*cisv1.ExternalDNS), err
}

// Update takes the representation of a externalDNS and updates it. Returns the server's representation of the externalDNS, and an error, if there is any.
func (c *FakeExternalDNSes) Update(ctx context.Context, externalDNS *cisv1.ExternalDNS, opts v1.UpdateOptions) (result *cisv1.ExternalDNS, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(externaldnsesResource, c.ns, externalDNS), &cisv1.ExternalDNS{})

	if obj == nil {
		return nil, err
	}
	return obj.(*cisv1.ExternalDNS), err
}

// Delete takes name of the externalDNS and deletes it. Returns an error if one occurs.
func (c *FakeExternalDNSes) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(externaldnsesResource, c.ns, name), &cisv1.ExternalDNS{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeExternalDNSes) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(externaldnsesResource, c.ns, listOpts)

	_, err := c.Fake.Invokes(action, &cisv1.ExternalDNSList{})
	return err
}

// Patch applies the patch and returns the patched externalDNS.
func (c *FakeExternalDNSes) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *cisv1.ExternalDNS, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(externaldnsesResource, c.ns, name, pt, data, subresources...), &cisv1.ExternalDNS{})

	if obj == nil {
		return nil, err
	}
	return obj.(*cisv1.ExternalDNS), err
}
