/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	cisv1 "github.com/F5Networks/k8s-bigip-ctlr/config/apis/cis/v1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeNginxCisConnectors implements NginxCisConnectorInterface
type FakeNginxCisConnectors struct {
	Fake *FakeK8sV1
	ns   string
}

var nginxcisconnectorsResource = schema.GroupVersionResource{Group: "k8s.nginx.org", Version: "v1", Resource: "nginxcisconnectors"}

var nginxcisconnectorsKind = schema.GroupVersionKind{Group: "k8s.nginx.org", Version: "v1", Kind: "NginxCisConnector"}

// Get takes name of the nginxCisConnector, and returns the corresponding nginxCisConnector object, and an error if there is any.
func (c *FakeNginxCisConnectors) Get(name string, options v1.GetOptions) (result *cisv1.NginxCisConnector, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(nginxcisconnectorsResource, c.ns, name), &cisv1.NginxCisConnector{})

	if obj == nil {
		return nil, err
	}
	return obj.(*cisv1.NginxCisConnector), err
}

// List takes label and field selectors, and returns the list of NginxCisConnectors that match those selectors.
func (c *FakeNginxCisConnectors) List(opts v1.ListOptions) (result *cisv1.NginxCisConnectorList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(nginxcisconnectorsResource, nginxcisconnectorsKind, c.ns, opts), &cisv1.NginxCisConnectorList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &cisv1.NginxCisConnectorList{ListMeta: obj.(*cisv1.NginxCisConnectorList).ListMeta}
	for _, item := range obj.(*cisv1.NginxCisConnectorList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested nginxCisConnectors.
func (c *FakeNginxCisConnectors) Watch(opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(nginxcisconnectorsResource, c.ns, opts))

}

// Create takes the representation of a nginxCisConnector and creates it.  Returns the server's representation of the nginxCisConnector, and an error, if there is any.
func (c *FakeNginxCisConnectors) Create(nginxCisConnector *cisv1.NginxCisConnector) (result *cisv1.NginxCisConnector, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(nginxcisconnectorsResource, c.ns, nginxCisConnector), &cisv1.NginxCisConnector{})

	if obj == nil {
		return nil, err
	}
	return obj.(*cisv1.NginxCisConnector), err
}

// Update takes the representation of a nginxCisConnector and updates it. Returns the server's representation of the nginxCisConnector, and an error, if there is any.
func (c *FakeNginxCisConnectors) Update(nginxCisConnector *cisv1.NginxCisConnector) (result *cisv1.NginxCisConnector, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(nginxcisconnectorsResource, c.ns, nginxCisConnector), &cisv1.NginxCisConnector{})

	if obj == nil {
		return nil, err
	}
	return obj.(*cisv1.NginxCisConnector), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeNginxCisConnectors) UpdateStatus(nginxCisConnector *cisv1.NginxCisConnector) (*cisv1.NginxCisConnector, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(nginxcisconnectorsResource, "status", c.ns, nginxCisConnector), &cisv1.NginxCisConnector{})

	if obj == nil {
		return nil, err
	}
	return obj.(*cisv1.NginxCisConnector), err
}

// Delete takes name of the nginxCisConnector and deletes it. Returns an error if one occurs.
func (c *FakeNginxCisConnectors) Delete(name string, options *v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(nginxcisconnectorsResource, c.ns, name), &cisv1.NginxCisConnector{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeNginxCisConnectors) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(nginxcisconnectorsResource, c.ns, listOptions)

	_, err := c.Fake.Invokes(action, &cisv1.NginxCisConnectorList{})
	return err
}

// Patch applies the patch and returns the patched nginxCisConnector.
func (c *FakeNginxCisConnectors) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *cisv1.NginxCisConnector, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(nginxcisconnectorsResource, c.ns, name, pt, data, subresources...), &cisv1.NginxCisConnector{})

	if obj == nil {
		return nil, err
	}
	return obj.(*cisv1.NginxCisConnector), err
}
