/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	cisv1 "github.com/F5Networks/k8s-bigip-ctlr/config/apis/cis/v1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeExternalDNSs implements ExternalDNSInterface
type FakeExternalDNSs struct {
	Fake *FakeK8sV1
	ns   string
}

var externaldnssResource = schema.GroupVersionResource{Group: "k8s.nginx.org", Version: "v1", Resource: "externaldnss"}

var externaldnssKind = schema.GroupVersionKind{Group: "k8s.nginx.org", Version: "v1", Kind: "ExternalDNS"}

// Get takes name of the externalDNS, and returns the corresponding externalDNS object, and an error if there is any.
func (c *FakeExternalDNSs) Get(name string, options v1.GetOptions) (result *cisv1.ExternalDNS, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(externaldnssResource, c.ns, name), &cisv1.ExternalDNS{})

	if obj == nil {
		return nil, err
	}
	return obj.(*cisv1.ExternalDNS), err
}

// List takes label and field selectors, and returns the list of ExternalDNSs that match those selectors.
func (c *FakeExternalDNSs) List(opts v1.ListOptions) (result *cisv1.ExternalDNSList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(externaldnssResource, externaldnssKind, c.ns, opts), &cisv1.ExternalDNSList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &cisv1.ExternalDNSList{ListMeta: obj.(*cisv1.ExternalDNSList).ListMeta}
	for _, item := range obj.(*cisv1.ExternalDNSList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested externalDNSs.
func (c *FakeExternalDNSs) Watch(opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(externaldnssResource, c.ns, opts))

}

// Create takes the representation of a externalDNS and creates it.  Returns the server's representation of the externalDNS, and an error, if there is any.
func (c *FakeExternalDNSs) Create(externalDNS *cisv1.ExternalDNS) (result *cisv1.ExternalDNS, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(externaldnssResource, c.ns, externalDNS), &cisv1.ExternalDNS{})

	if obj == nil {
		return nil, err
	}
	return obj.(*cisv1.ExternalDNS), err
}

// Update takes the representation of a externalDNS and updates it. Returns the server's representation of the externalDNS, and an error, if there is any.
func (c *FakeExternalDNSs) Update(externalDNS *cisv1.ExternalDNS) (result *cisv1.ExternalDNS, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(externaldnssResource, c.ns, externalDNS), &cisv1.ExternalDNS{})

	if obj == nil {
		return nil, err
	}
	return obj.(*cisv1.ExternalDNS), err
}

// Delete takes name of the externalDNS and deletes it. Returns an error if one occurs.
func (c *FakeExternalDNSs) Delete(name string, options *v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(externaldnssResource, c.ns, name), &cisv1.ExternalDNS{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeExternalDNSs) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(externaldnssResource, c.ns, listOptions)

	_, err := c.Fake.Invokes(action, &cisv1.ExternalDNSList{})
	return err
}

// Patch applies the patch and returns the patched externalDNS.
func (c *FakeExternalDNSs) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *cisv1.ExternalDNS, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(externaldnssResource, c.ns, name, pt, data, subresources...), &cisv1.ExternalDNS{})

	if obj == nil {
		return nil, err
	}
	return obj.(*cisv1.ExternalDNS), err
}
