// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.21.9
// source: proto/ipamgrpc.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// IpamGRPCServiceClient is the client API for IpamGRPCService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type IpamGRPCServiceClient interface {
	AllocateIP(ctx context.Context, in *AllocateIPRequest, opts ...grpc.CallOption) (*AllocateIPResponse, error)
	ReleaseIP(ctx context.Context, in *ReleaseIPRequest, opts ...grpc.CallOption) (*ReleaseIPResponse, error)
}

type ipamGRPCServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewIpamGRPCServiceClient(cc grpc.ClientConnInterface) IpamGRPCServiceClient {
	return &ipamGRPCServiceClient{cc}
}

func (c *ipamGRPCServiceClient) AllocateIP(ctx context.Context, in *AllocateIPRequest, opts ...grpc.CallOption) (*AllocateIPResponse, error) {
	out := new(AllocateIPResponse)
	err := c.cc.Invoke(ctx, "/ipamgrpc.IpamGRPCService/AllocateIP", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ipamGRPCServiceClient) ReleaseIP(ctx context.Context, in *ReleaseIPRequest, opts ...grpc.CallOption) (*ReleaseIPResponse, error) {
	out := new(ReleaseIPResponse)
	err := c.cc.Invoke(ctx, "/ipamgrpc.IpamGRPCService/ReleaseIP", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// IpamGRPCServiceServer is the server API for IpamGRPCService service.
// All implementations must embed UnimplementedIpamGRPCServiceServer
// for forward compatibility
type IpamGRPCServiceServer interface {
	AllocateIP(context.Context, *AllocateIPRequest) (*AllocateIPResponse, error)
	ReleaseIP(context.Context, *ReleaseIPRequest) (*ReleaseIPResponse, error)
	mustEmbedUnimplementedIpamGRPCServiceServer()
}

// UnimplementedIpamGRPCServiceServer must be embedded to have forward compatible implementations.
type UnimplementedIpamGRPCServiceServer struct {
}

func (UnimplementedIpamGRPCServiceServer) AllocateIP(context.Context, *AllocateIPRequest) (*AllocateIPResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AllocateIP not implemented")
}
func (UnimplementedIpamGRPCServiceServer) ReleaseIP(context.Context, *ReleaseIPRequest) (*ReleaseIPResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ReleaseIP not implemented")
}
func (UnimplementedIpamGRPCServiceServer) mustEmbedUnimplementedIpamGRPCServiceServer() {}

// UnsafeIpamGRPCServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to IpamGRPCServiceServer will
// result in compilation errors.
type UnsafeIpamGRPCServiceServer interface {
	mustEmbedUnimplementedIpamGRPCServiceServer()
}

func RegisterIpamGRPCServiceServer(s grpc.ServiceRegistrar, srv IpamGRPCServiceServer) {
	s.RegisterService(&IpamGRPCService_ServiceDesc, srv)
}

func _IpamGRPCService_AllocateIP_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AllocateIPRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IpamGRPCServiceServer).AllocateIP(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ipamgrpc.IpamGRPCService/AllocateIP",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IpamGRPCServiceServer).AllocateIP(ctx, req.(*AllocateIPRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _IpamGRPCService_ReleaseIP_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReleaseIPRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IpamGRPCServiceServer).ReleaseIP(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ipamgrpc.IpamGRPCService/ReleaseIP",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IpamGRPCServiceServer).ReleaseIP(ctx, req.(*ReleaseIPRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// IpamGRPCService_ServiceDesc is the grpc.ServiceDesc for IpamGRPCService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var IpamGRPCService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "ipamgrpc.IpamGRPCService",
	HandlerType: (*IpamGRPCServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "AllocateIP",
			Handler:    _IpamGRPCService_AllocateIP_Handler,
		},
		{
			MethodName: "ReleaseIP",
			Handler:    _IpamGRPCService_ReleaseIP_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/ipamgrpc.proto",
}
