/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1

import (
	"time"

	v1 "github.com/F5Networks/k8s-bigip-ctlr/config/apis/cis/v1"
	scheme "github.com/F5Networks/k8s-bigip-ctlr/config/client/clientset/versioned/scheme"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// ExternalDNSsGetter has a method to return a ExternalDNSInterface.
// A group's client should implement this interface.
type ExternalDNSsGetter interface {
	ExternalDNSs(namespace string) ExternalDNSInterface
}

// ExternalDNSInterface has methods to work with ExternalDNS resources.
type ExternalDNSInterface interface {
	Create(*v1.ExternalDNS) (*v1.ExternalDNS, error)
	Update(*v1.ExternalDNS) (*v1.ExternalDNS, error)
	Delete(name string, options *metav1.DeleteOptions) error
	DeleteCollection(options *metav1.DeleteOptions, listOptions metav1.ListOptions) error
	Get(name string, options metav1.GetOptions) (*v1.ExternalDNS, error)
	List(opts metav1.ListOptions) (*v1.ExternalDNSList, error)
	Watch(opts metav1.ListOptions) (watch.Interface, error)
	Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1.ExternalDNS, err error)
	ExternalDNSExpansion
}

// externalDNSs implements ExternalDNSInterface
type externalDNSs struct {
	client rest.Interface
	ns     string
}

// newExternalDNSs returns a ExternalDNSs
func newExternalDNSs(c *K8sV1Client, namespace string) *externalDNSs {
	return &externalDNSs{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the externalDNS, and returns the corresponding externalDNS object, and an error if there is any.
func (c *externalDNSs) Get(name string, options metav1.GetOptions) (result *v1.ExternalDNS, err error) {
	result = &v1.ExternalDNS{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("externaldnss").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do().
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of ExternalDNSs that match those selectors.
func (c *externalDNSs) List(opts metav1.ListOptions) (result *v1.ExternalDNSList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1.ExternalDNSList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("externaldnss").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do().
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested externalDNSs.
func (c *externalDNSs) Watch(opts metav1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("externaldnss").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch()
}

// Create takes the representation of a externalDNS and creates it.  Returns the server's representation of the externalDNS, and an error, if there is any.
func (c *externalDNSs) Create(externalDNS *v1.ExternalDNS) (result *v1.ExternalDNS, err error) {
	result = &v1.ExternalDNS{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("externaldnss").
		Body(externalDNS).
		Do().
		Into(result)
	return
}

// Update takes the representation of a externalDNS and updates it. Returns the server's representation of the externalDNS, and an error, if there is any.
func (c *externalDNSs) Update(externalDNS *v1.ExternalDNS) (result *v1.ExternalDNS, err error) {
	result = &v1.ExternalDNS{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("externaldnss").
		Name(externalDNS.Name).
		Body(externalDNS).
		Do().
		Into(result)
	return
}

// Delete takes name of the externalDNS and deletes it. Returns an error if one occurs.
func (c *externalDNSs) Delete(name string, options *metav1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("externaldnss").
		Name(name).
		Body(options).
		Do().
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *externalDNSs) DeleteCollection(options *metav1.DeleteOptions, listOptions metav1.ListOptions) error {
	var timeout time.Duration
	if listOptions.TimeoutSeconds != nil {
		timeout = time.Duration(*listOptions.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Namespace(c.ns).
		Resource("externaldnss").
		VersionedParams(&listOptions, scheme.ParameterCodec).
		Timeout(timeout).
		Body(options).
		Do().
		Error()
}

// Patch applies the patch and returns the patched externalDNS.
func (c *externalDNSs) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1.ExternalDNS, err error) {
	result = &v1.ExternalDNS{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("externaldnss").
		SubResource(subresources...).
		Name(name).
		Body(data).
		Do().
		Into(result)
	return
}
