/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1

import (
	"context"
	"time"

	v1 "github.com/F5Networks/k8s-bigip-ctlr/v3/config/apis/cis/v1"
	scheme "github.com/F5Networks/k8s-bigip-ctlr/v3/config/client/clientset/versioned/scheme"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// IngressLinksGetter has a method to return a IngressLinkInterface.
// A group's client should implement this interface.
type IngressLinksGetter interface {
	IngressLinks(namespace string) IngressLinkInterface
}

// IngressLinkInterface has methods to work with IngressLink resources.
type IngressLinkInterface interface {
	Create(ctx context.Context, ingressLink *v1.IngressLink, opts metav1.CreateOptions) (*v1.IngressLink, error)
	Update(ctx context.Context, ingressLink *v1.IngressLink, opts metav1.UpdateOptions) (*v1.IngressLink, error)
	UpdateStatus(ctx context.Context, ingressLink *v1.IngressLink, opts metav1.UpdateOptions) (*v1.IngressLink, error)
	Delete(ctx context.Context, name string, opts metav1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts metav1.DeleteOptions, listOpts metav1.ListOptions) error
	Get(ctx context.Context, name string, opts metav1.GetOptions) (*v1.IngressLink, error)
	List(ctx context.Context, opts metav1.ListOptions) (*v1.IngressLinkList, error)
	Watch(ctx context.Context, opts metav1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts metav1.PatchOptions, subresources ...string) (result *v1.IngressLink, err error)
	IngressLinkExpansion
}

// ingressLinks implements IngressLinkInterface
type ingressLinks struct {
	client rest.Interface
	ns     string
}

// newIngressLinks returns a IngressLinks
func newIngressLinks(c *CisV1Client, namespace string) *ingressLinks {
	return &ingressLinks{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the ingressLink, and returns the corresponding ingressLink object, and an error if there is any.
func (c *ingressLinks) Get(ctx context.Context, name string, options metav1.GetOptions) (result *v1.IngressLink, err error) {
	result = &v1.IngressLink{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("ingresslinks").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do(ctx).
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of IngressLinks that match those selectors.
func (c *ingressLinks) List(ctx context.Context, opts metav1.ListOptions) (result *v1.IngressLinkList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1.IngressLinkList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("ingresslinks").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do(ctx).
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested ingressLinks.
func (c *ingressLinks) Watch(ctx context.Context, opts metav1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("ingresslinks").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch(ctx)
}

// Create takes the representation of a ingressLink and creates it.  Returns the server's representation of the ingressLink, and an error, if there is any.
func (c *ingressLinks) Create(ctx context.Context, ingressLink *v1.IngressLink, opts metav1.CreateOptions) (result *v1.IngressLink, err error) {
	result = &v1.IngressLink{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("ingresslinks").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(ingressLink).
		Do(ctx).
		Into(result)
	return
}

// Update takes the representation of a ingressLink and updates it. Returns the server's representation of the ingressLink, and an error, if there is any.
func (c *ingressLinks) Update(ctx context.Context, ingressLink *v1.IngressLink, opts metav1.UpdateOptions) (result *v1.IngressLink, err error) {
	result = &v1.IngressLink{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("ingresslinks").
		Name(ingressLink.Name).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(ingressLink).
		Do(ctx).
		Into(result)
	return
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *ingressLinks) UpdateStatus(ctx context.Context, ingressLink *v1.IngressLink, opts metav1.UpdateOptions) (result *v1.IngressLink, err error) {
	result = &v1.IngressLink{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("ingresslinks").
		Name(ingressLink.Name).
		SubResource("status").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(ingressLink).
		Do(ctx).
		Into(result)
	return
}

// Delete takes name of the ingressLink and deletes it. Returns an error if one occurs.
func (c *ingressLinks) Delete(ctx context.Context, name string, opts metav1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("ingresslinks").
		Name(name).
		Body(&opts).
		Do(ctx).
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *ingressLinks) DeleteCollection(ctx context.Context, opts metav1.DeleteOptions, listOpts metav1.ListOptions) error {
	var timeout time.Duration
	if listOpts.TimeoutSeconds != nil {
		timeout = time.Duration(*listOpts.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Namespace(c.ns).
		Resource("ingresslinks").
		VersionedParams(&listOpts, scheme.ParameterCodec).
		Timeout(timeout).
		Body(&opts).
		Do(ctx).
		Error()
}

// Patch applies the patch and returns the patched ingressLink.
func (c *ingressLinks) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts metav1.PatchOptions, subresources ...string) (result *v1.IngressLink, err error) {
	result = &v1.IngressLink{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("ingresslinks").
		Name(name).
		SubResource(subresources...).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(data).
		Do(ctx).
		Into(result)
	return
}
