/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1

import (
	"time"

	v1 "github.com/F5Networks/k8s-bigip-ctlr/config/apis/cis/v1"
	scheme "github.com/F5Networks/k8s-bigip-ctlr/config/client/clientset/versioned/scheme"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// TLSProfilesGetter has a method to return a TLSProfileInterface.
// A group's client should implement this interface.
type TLSProfilesGetter interface {
	TLSProfiles(namespace string) TLSProfileInterface
}

// TLSProfileInterface has methods to work with TLSProfile resources.
type TLSProfileInterface interface {
	Create(*v1.TLSProfile) (*v1.TLSProfile, error)
	Update(*v1.TLSProfile) (*v1.TLSProfile, error)
	Delete(name string, options *metav1.DeleteOptions) error
	DeleteCollection(options *metav1.DeleteOptions, listOptions metav1.ListOptions) error
	Get(name string, options metav1.GetOptions) (*v1.TLSProfile, error)
	List(opts metav1.ListOptions) (*v1.TLSProfileList, error)
	Watch(opts metav1.ListOptions) (watch.Interface, error)
	Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1.TLSProfile, err error)
	TLSProfileExpansion
}

// tLSProfiles implements TLSProfileInterface
type tLSProfiles struct {
	client rest.Interface
	ns     string
}

// newTLSProfiles returns a TLSProfiles
func newTLSProfiles(c *K8sV1Client, namespace string) *tLSProfiles {
	return &tLSProfiles{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the tLSProfile, and returns the corresponding tLSProfile object, and an error if there is any.
func (c *tLSProfiles) Get(name string, options metav1.GetOptions) (result *v1.TLSProfile, err error) {
	result = &v1.TLSProfile{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("tlsprofiles").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do().
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of TLSProfiles that match those selectors.
func (c *tLSProfiles) List(opts metav1.ListOptions) (result *v1.TLSProfileList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1.TLSProfileList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("tlsprofiles").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do().
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested tLSProfiles.
func (c *tLSProfiles) Watch(opts metav1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("tlsprofiles").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch()
}

// Create takes the representation of a tLSProfile and creates it.  Returns the server's representation of the tLSProfile, and an error, if there is any.
func (c *tLSProfiles) Create(tLSProfile *v1.TLSProfile) (result *v1.TLSProfile, err error) {
	result = &v1.TLSProfile{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("tlsprofiles").
		Body(tLSProfile).
		Do().
		Into(result)
	return
}

// Update takes the representation of a tLSProfile and updates it. Returns the server's representation of the tLSProfile, and an error, if there is any.
func (c *tLSProfiles) Update(tLSProfile *v1.TLSProfile) (result *v1.TLSProfile, err error) {
	result = &v1.TLSProfile{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("tlsprofiles").
		Name(tLSProfile.Name).
		Body(tLSProfile).
		Do().
		Into(result)
	return
}

// Delete takes name of the tLSProfile and deletes it. Returns an error if one occurs.
func (c *tLSProfiles) Delete(name string, options *metav1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("tlsprofiles").
		Name(name).
		Body(options).
		Do().
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *tLSProfiles) DeleteCollection(options *metav1.DeleteOptions, listOptions metav1.ListOptions) error {
	var timeout time.Duration
	if listOptions.TimeoutSeconds != nil {
		timeout = time.Duration(*listOptions.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Namespace(c.ns).
		Resource("tlsprofiles").
		VersionedParams(&listOptions, scheme.ParameterCodec).
		Timeout(timeout).
		Body(options).
		Do().
		Error()
}

// Patch applies the patch and returns the patched tLSProfile.
func (c *tLSProfiles) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1.TLSProfile, err error) {
	result = &v1.TLSProfile{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("tlsprofiles").
		SubResource(subresources...).
		Name(name).
		Body(data).
		Do().
		Into(result)
	return
}
